version: '3'

services:
  docs:
    image: bowling_club_app_local_docs
    container_name: bowling_club_app_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./bowling_club_app:/app/bowling_club_app:z
    ports:
      - '9000:9000'
    command: /start-docs
