name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ['master', 'main']
    paths-ignore: ['docs/**']

  push:
    branches: ['master', 'main']
    paths-ignore: ['docs/**']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  deploy_to_aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker Image
        run: docker compose -f local.yml build django

      - name: Authenticate with AWS ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push Docker Image to AWS ECR
        run: |
          aws ecr create-repository --repository-name my-repository-name --region eu-north-1 || true
          docker tag my-image-uri:latest 533267220516.dkr.ecr.eu-north-1.amazonaws.com/alvabowlingclub-repository:latest
          docker push 533267220516.dkr.ecr.eu-north-1.amazonaws.com/alvabowlingclub-repository:latest

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
          application_name: 'my-application'
          environment_name: 'my-environment'
          version_label: 'v${{ github.run_number }}'
          deploy_to: 'all'
