name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: ['master', 'main']
    paths-ignore: ['docs/**']

  push:
    branches: ['master', 'main']
    paths-ignore: ['docs/**']

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  deploy_to_aws:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build the Docker Image
        run: |
          docker-compose -f local.yml config  # Check the Docker Compose configuration
          docker-compose -f local.yml build django  # Build the Django service
          docker images  # List all Docker images to verify the built image
          docker-compose -f local.yml ps  # Check the status of all services defined in Docker Compose
      
      - name: Tag Docker Image
        run: docker tag bowling_club_app_local_django:latest 533267220516.dkr.ecr.eu-north-1.amazonaws.com/alvabowlingclub-repository:latest
               
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Push Docker Image to AWS ECR
        run: |
          docker push 533267220516.dkr.ecr.eu-north-1.amazonaws.com/alvabowlingclub-repository:latest || echo "Docker push failed with exit code $?"

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
          application_name: 'django'
          environment_name: 'django-env'
          version_label: 'v${{ github.run_number }}'
